"""nulable side dish in details

Revision ID: 17e0c2dc5859
Revises: 971c7c078578
Create Date: 2023-10-16 14:58:18.785000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17e0c2dc5859'
down_revision: Union[str, None] = '971c7c078578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderdetail', 'side_dish',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderdetail', 'side_dish',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
