"""add number to table

Revision ID: 63673934b0c1
Revises: 8d12a802543e
Create Date: 2024-01-07 22:42:50.415473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63673934b0c1'
down_revision: Union[str, None] = '8d12a802543e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'state',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('processing', 'waiting', 'preparation', 'cancelled', 'delivered', 'closed', name='orderstate'),
               existing_nullable=False)
    op.add_column('table', sa.Column('number', sa.Integer(), nullable=False))
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('admin', 'employee', name='userrolesenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('admin', 'employee', name='userrolesenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('table', 'number')
    op.alter_column('order', 'state',
               existing_type=sa.Enum('processing', 'waiting', 'preparation', 'cancelled', 'delivered', 'closed', name='orderstate'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
