"""Cambio en details

Revision ID: 7767e845e189
Revises: b78a01142384
Create Date: 2023-10-13 20:12:41.546415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7767e845e189'
down_revision: Union[str, None] = 'b78a01142384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderdetail', sa.Column('dish', sa.Integer(), nullable=False))
    op.add_column('orderdetail', sa.Column('side_dish', sa.Integer(), nullable=False))
    op.add_column('orderdetail', sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('orderdetail', sa.Column('ammount', sa.Integer(), nullable=False))
    op.drop_constraint('orderdetail_dish_selected_fkey', 'orderdetail', type_='foreignkey')
    op.create_foreign_key(None, 'orderdetail', 'dish', ['dish'], ['id'])
    op.create_foreign_key(None, 'orderdetail', 'sidedish', ['side_dish'], ['id'])
    op.drop_column('orderdetail', 'dish_selected')
    op.drop_column('orderdetail', 'customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderdetail', sa.Column('customer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orderdetail', sa.Column('dish_selected', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderdetail', type_='foreignkey')
    op.drop_constraint(None, 'orderdetail', type_='foreignkey')
    op.create_foreign_key('orderdetail_dish_selected_fkey', 'orderdetail', 'sidedishoptions', ['dish_selected'], ['id'])
    op.drop_column('orderdetail', 'ammount')
    op.drop_column('orderdetail', 'customer_name')
    op.drop_column('orderdetail', 'side_dish')
    op.drop_column('orderdetail', 'dish')
    # ### end Alembic commands ###
