"""add sectors

Revision ID: 822c053c8897
Revises: 17e0c2dc5859
Create Date: 2023-10-18 19:33:19.496401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '822c053c8897'
down_revision: Union[str, None] = '17e0c2dc5859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablesector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('restaurant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('table', sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'table', 'tablesector', ['sector'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table', type_='foreignkey')
    op.drop_column('table', 'sector')
    op.drop_table('tablesector')
    # ### end Alembic commands ###
